openapi: 3.1.0
info:
  version: 1.0.0
  title: Phonebook app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of Phonebook app
tags:
  - name: Phonebook
    description: Operations about phonebook.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    npmpost:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
